"use client"

import { Suspense, useEffect, useRef, useState } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import ProgressBar from "@/components/ProgressBar"
import ChatBubble from "@/components/ChatBubble"
import SessionSummary from "@/components/SessionSummary"
import { gradeAnswer, INTERVALS } from "@/lib/srs"
import type { CardWithDir, ReviewResult } from "@/lib/srs"

type CardPhase = "prompt" | "feedback" | "reveal"
type Screen = "card" | "chat" | "summary"

// Hidden instruction that kicks off the new-material chat. The tutor's opener is
// generated by Claude from the learner's actual progress (system prompt), not hardcoded.
const NEW_MATERIAL_SEED =
  "Lass uns mit etwas neuem Stoff weitermachen. Führe das nächste Thema gemäß meinem aktuellen Fortschritt ein — kurz erklärt über den Kontrast Deutsch↔Türkisch — und stelle mir zum Schluss genau eine kurze Produktionsfrage."

type CardResult = {
  correct: boolean
  your: string
  target: string
  prompt: string
  sub: string
  note: string
}

type ChatMsg = { role: "tutor" | "me"; text: string; hidden?: boolean }

type SummaryData = {
  reviewed: number
  correct: number
  boxMoves: { tr: string; de: string; from: number; to: number }[]
  newWords: { tr: string; de: string }[]
  nextDueText: string
  streak: number
}

function Loader() {
  return (
    <div className="min-h-[100dvh] bg-bg flex items-center justify-center">
      <div className="flex gap-1.5">
        {[0, 1, 2].map((i) => (
          <span key={i} className="w-2 h-2 rounded-full bg-muted animate-dotpulse"
            style={{ animationDelay: `${i * 0.18}s` }} />
        ))}
      </div>
    </div>
  )
}

export default function SessionPage() {
  return (
    <Suspense fallback={<Loader />}>
      <SessionView />
    </Suspense>
  )
}

function SessionView() {
  const router = useRouter()
  const params = useSearchParams()

  const [screen, setScreen] = useState<Screen>("card")
  const [vocab, setVocab] = useState<CardWithDir[]>([])
  const [queue, setQueue] = useState<number[]>([])
  const [qi, setQi] = useState(0)
  const [cardPhase, setCardPhase] = useState<CardPhase>("prompt")
  const [input, setInput] = useState("")
  const [result, setResult] = useState<CardResult | null>(null)
  const [results, setResults] = useState<ReviewResult[]>([])
  const [moves, setMoves] = useState<Record<number, { from: number; to: number }>>({})
  const [phaseLabel, setPhaseLabel] = useState("")
  const [chat, setChat] = useState<ChatMsg[]>([])
  const [chatInput, setChatInput] = useState("")
  const [pending, setPending] = useState(false)
  const [exitOpen, setExitOpen] = useState(false)
  const [loading, setLoading] = useState(true)
  const [ending, setEnding] = useState(false)
  const [summaryData, setSummaryData] = useState<SummaryData | null>(null)
  const [streak, setStreak] = useState(0)

  const scrollRef = useRef<HTMLDivElement>(null)
  const touchStartX = useRef(0)

  useEffect(() => {
    fetch("/api/session/start", { method: "POST" })
      .then((r) => {
        if (r.status === 401) { router.replace("/login"); return null }
        if (!r.ok) throw new Error(`${r.status}`)
        return r.json()
      })
      .then((data) => {
        if (!data) return
        setVocab(data.vocab ?? [])
        setQueue(data.queue ?? [])
        setPhaseLabel(data.progress?.phase_pointer ?? "")
        setStreak(data.streak ?? 0)
        setLoading(false)

        if ((data.queue ?? []).length === 0 || params.get("mode") === "new") {
          goChat()
        }
      })
      .catch(() => {
        setLoading(false)
      })
  }, [])

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [chat, pending])

  function curCard(): CardWithDir | null {
    if (!queue?.length) return null
    const idx = queue[qi]
    return idx != null ? vocab[idx] : null
  }

  function promptOf(c: CardWithDir) { return c.dir === "de2tr" ? c.de : c.tr }
  function targetOf(c: CardWithDir) { return c.dir === "de2tr" ? c.tr : c.de }
  function askLang(c: CardWithDir) { return c.dir === "de2tr" ? "auf Türkisch" : "auf Deutsch" }
  function dirLabel(c: CardWithDir) { return c.dir === "de2tr" ? "Übersetze ins Türkische" : "Übersetze ins Deutsche" }

  function submitAnswer() {
    const c = curCard()
    if (!c || !input.trim()) return

    const ok = gradeAnswer(input.trim(), c)
    const idx = queue[qi]
    const from = c.box
    const to = ok ? Math.min(5, from + 1) : 1

    setMoves((prev) => ({ ...prev, [idx]: { from, to } }))
    setResults((prev) => [
      ...prev,
      { tr: c.tr, de: c.de, correct: ok, your: input.trim(), from, to, interval: INTERVALS[to - 1] },
    ])
    setResult({
      correct: ok,
      your: input.trim(),
      target: targetOf(c),
      prompt: promptOf(c),
      sub: askLang(c),
      note: c.notes ?? "",
    })
    setCardPhase("feedback")
  }

  function showAnswer() {
    const c = curCard()
    if (!c) return
    setResult({ correct: false, your: "", target: targetOf(c), prompt: promptOf(c), sub: askLang(c), note: c.notes ?? "" })
    setCardPhase("reveal")
  }

  function selfGrade(known: boolean) {
    const c = curCard()
    if (!c) return
    const idx = queue[qi]
    const from = c.box
    const to = known ? Math.min(5, from + 1) : 1
    setMoves((prev) => ({ ...prev, [idx]: { from, to } }))
    setResults((prev) => [
      ...prev,
      { tr: c.tr, de: c.de, correct: known, your: "gezeigt", from, to, interval: INTERVALS[to - 1] },
    ])
    nextCard()
  }

  function nextCard() {
    if (qi + 1 >= queue.length) {
      goChat()
    } else {
      setQi(qi + 1)
      setCardPhase("prompt")
      setInput("")
      setResult(null)
    }
  }

  function goChat() {
    const seed: ChatMsg = { role: "me", text: NEW_MATERIAL_SEED, hidden: true }
    setChat([seed])
    setScreen("chat")
    streamTutor([seed])
  }

  // Streams a tutor reply given the conversation so far (hidden turns included).
  async function streamTutor(history: ChatMsg[]) {
    setPending(true)
    const apiMessages = history.map((m) => ({
      role: m.role === "me" ? ("user" as const) : ("assistant" as const),
      content: m.text,
    }))

    try {
      const res = await fetch("/api/session/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: apiMessages }),
      })

      if (!res.ok || !res.body) throw new Error("No stream")

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let full = ""

      setChat((prev) => [...prev, { role: "tutor", text: "" }])

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        full += decoder.decode(value, { stream: true })
        setChat((prev) => {
          const next = [...prev]
          next[next.length - 1] = { role: "tutor", text: full }
          return next
        })
      }
    } catch {
      setChat((prev) => [
        ...prev,
        { role: "tutor", text: "Tut mir leid, der Tutor antwortet gerade nicht. Versuche es nochmal." },
      ])
    } finally {
      setPending(false)
    }
  }

  function sendChat() {
    if (!chatInput.trim() || pending) return
    const me: ChatMsg = { role: "me", text: chatInput.trim() }
    const updated = [...chat, me]
    setChat(updated)
    setChatInput("")
    streamTutor(updated)
  }

  async function endSession() {
    if (ending) return
    setEnding(true)

    const transcript = chat.map((m) => ({
      role: m.role === "me" ? ("user" as const) : ("assistant" as const),
      content: m.text,
    }))
    const clientResults = results.map((r, i) => ({
      vocabIndex: queue[i] ?? 0,
      correct: r.correct,
      your: r.your,
    }))

    try {
      // Fast path — SRS + streak only, no LLM. Show the summary immediately.
      const res = await fetch("/api/session/end", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ results: clientResults }),
      })
      const data = await res.json()
      setSummaryData(data)
      setScreen("summary")
    } catch {
      setSummaryData({
        reviewed: results.length,
        correct: results.filter((r) => r.correct).length,
        boxMoves: [],
        newWords: [],
        nextDueText: "morgen",
        streak,
      })
      setScreen("summary")
    } finally {
      setEnding(false)
    }

    // Background — Claude extraction (new vocab, pointer, weak spots). Never
    // blocks the summary; the "Neu im Chat" row fills in when it resolves.
    if (transcript.length > 0) {
      fetch("/api/session/extract", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ transcript }),
      })
        .then((r) => (r.ok ? r.json() : null))
        .then((d) => {
          if (d?.newWords) {
            setSummaryData((prev) => (prev ? { ...prev, newWords: d.newWords } : prev))
          }
        })
        .catch(() => {})
    }
  }

  // Swipe handling
  function onTouchStart(e: React.TouchEvent) { touchStartX.current = e.changedTouches[0].clientX }
  function onTouchEnd(e: React.TouchEvent) {
    const dx = e.changedTouches[0].clientX - touchStartX.current
    if (dx > 50 && cardPhase === "feedback") nextCard()
  }

  if (loading) {
    return (
      <div className="min-h-[100dvh] bg-bg flex items-center justify-center">
        <div className="flex gap-1.5">
          {[0, 1, 2].map((i) => (
            <span key={i} className="w-2 h-2 rounded-full bg-muted animate-dotpulse"
              style={{ animationDelay: `${i * 0.18}s` }} />
          ))}
        </div>
      </div>
    )
  }

  if (screen === "summary" && summaryData) {
    return (
      <SessionSummary
        reviewed={summaryData.reviewed}
        correct={summaryData.correct}
        boxMoves={summaryData.boxMoves}
        newWords={summaryData.newWords}
        nextDueText={summaryData.nextDueText}
        streak={summaryData.streak}
        onFinish={() => router.push("/")}
      />
    )
  }

  // ---- FLASHCARD SCREEN ----
  if (screen === "card") {
    const c = curCard()
    return (
      <div
        className="relative min-h-[100dvh] bg-bg w-full max-w-md mx-auto overflow-hidden pt-safe md:border-x md:border-border"
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
      >
        <ProgressBar current={qi + 1} total={queue.length} onExit={() => setExitOpen(true)} />

        {c && (
          <>
            {/* PROMPT */}
            {cardPhase === "prompt" && (
              <>
                <div className="mx-[22px] mt-11 bg-surface border border-border rounded-card px-[26px] py-12 text-center">
                  <div
                    className="text-[13px] font-extrabold uppercase text-muted"
                    style={{ letterSpacing: "0.1em", fontFamily: "'Hanken Grotesk', sans-serif" }}
                  >
                    {dirLabel(c)}
                  </div>
                  <div className="text-[46px] font-extrabold tracking-tight mt-[18px]">
                    {promptOf(c)}
                  </div>
                </div>

                <div className="absolute left-0 right-0 bottom-0 px-4 pb-[18px]">
                  <button
                    onClick={showAnswer}
                    className="w-full text-center mb-4 text-[14px] font-semibold text-muted"
                  >
                    Antwort zeigen
                  </button>
                  <div className="flex items-center gap-2.5">
                    <input
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); submitAnswer() } }}
                      placeholder={c.dir === "de2tr" ? "Türkisch tippen…" : "Deutsch tippen…"}
                      autoComplete="off"
                      autoCapitalize="off"
                      spellCheck={false}
                      className="flex-1 h-14 rounded-input bg-surface text-text px-5 text-[17px] font-semibold outline-none"
                      style={{ border: "2px solid #d57b48", fontSize: "17px" }}
                    />
                    <button
                      onClick={submitAnswer}
                      className="w-14 h-14 rounded-full bg-accent text-on-accent flex items-center justify-center text-[23px] font-extrabold flex-shrink-0"
                    >
                      →
                    </button>
                  </div>
                </div>
              </>
            )}

            {/* FEEDBACK: CORRECT */}
            {cardPhase === "feedback" && result?.correct && (
              <>
                <div className="px-[26px] pt-12 text-center">
                  <div className="w-[60px] h-[60px] rounded-full mx-auto mb-5 flex items-center justify-center text-[28px] font-bold text-correct animate-pop"
                    style={{ background: "rgba(155,178,101,.13)", border: "1.5px solid rgba(155,178,101,.5)" }}>
                    ✓
                  </div>
                  <div className="text-[22px] font-extrabold text-correct">Genau!</div>
                </div>
                <div className="px-[26px] pt-[22px] text-center">
                  <div className="text-[38px] font-extrabold tracking-tight">{result.target}</div>
                  <div className="text-[12px] font-extrabold uppercase text-muted mt-2"
                    style={{ letterSpacing: "0.16em" }}>
                    = {result.prompt}
                  </div>
                </div>
                <div className="mx-[22px] mt-[26px] bg-surface border border-border rounded-[22px] flex items-center justify-between px-5 py-4">
                  <span className="text-[14px] font-semibold text-muted">Deine Antwort</span>
                  <span className="text-[16px] font-extrabold text-correct flex items-center gap-2">
                    {result.your} <span>✓</span>
                  </span>
                </div>
                {result.note && (
                  <div className="mx-[26px] mt-5 text-[14.5px] leading-relaxed text-center"
                    style={{ color: "#cdbfae" }}>
                    {result.note}
                  </div>
                )}
              </>
            )}

            {/* FEEDBACK: WRONG */}
            {cardPhase === "feedback" && result && !result.correct && (
              <>
                <div className="px-[26px] pt-10 text-center">
                  <div className="text-[22px] font-extrabold text-wrong">Fast! Schau mal:</div>
                </div>
                <div className="px-[26px] pt-[22px] text-center">
                  <div className="text-[38px] font-extrabold tracking-tight">{result.prompt}</div>
                  <div className="text-[12px] font-extrabold uppercase text-muted mt-2"
                    style={{ letterSpacing: "0.16em" }}>
                    {result.sub}
                  </div>
                </div>
                <div className="mx-[22px] mt-[26px] bg-surface border border-border rounded-[22px] overflow-hidden">
                  <div className="flex items-center justify-between px-5 py-4"
                    style={{ borderBottom: "1px solid #2e251b" }}>
                    <span className="text-[14px] font-semibold text-muted">Deine Antwort</span>
                    <span className="text-[16px] font-bold text-wrong line-through"
                      style={{ textDecorationColor: "rgba(217,106,82,.55)" }}>
                      {result.your}
                    </span>
                  </div>
                  <div className="flex items-center justify-between px-5 py-4">
                    <span className="text-[14px] font-semibold text-muted">Richtig</span>
                    <span className="text-[16px] font-extrabold text-correct">{result.target}</span>
                  </div>
                </div>
                {result.note && (
                  <div className="mx-[26px] mt-5 text-[14.5px] leading-relaxed text-center"
                    style={{ color: "#cdbfae" }}>
                    {result.note}
                  </div>
                )}
              </>
            )}

            {/* REVEAL / SELF-GRADE */}
            {cardPhase === "reveal" && result && (
              <>
                <div className="mx-[22px] mt-11 bg-surface border border-border rounded-card px-[26px] py-10 text-center">
                  <div className="text-[13px] font-extrabold uppercase text-muted"
                    style={{ letterSpacing: "0.1em" }}>
                    {result.prompt} · {result.sub}
                  </div>
                  <div className="text-[40px] font-extrabold tracking-tight mt-[18px]">
                    {result.target}
                  </div>
                  {result.note && (
                    <div className="text-[14px] font-semibold mt-3.5" style={{ color: "#cdbfae" }}>
                      {result.note}
                    </div>
                  )}
                </div>

                <div className="absolute left-0 right-0 bottom-0 px-[22px] pb-[34px]">
                  <div className="text-center text-[15px] font-bold mb-4" style={{ color: "#cdbfae" }}>
                    Konntest du es?
                  </div>
                  <div className="flex gap-3">
                    <button
                      onClick={() => selfGrade(false)}
                      className="flex-1 h-[58px] rounded-input flex items-center justify-center text-[16px] font-bold text-wrong"
                      style={{ background: "rgba(217,106,82,.1)", border: "1.5px solid rgba(217,106,82,.45)" }}
                    >
                      Nicht gewusst
                    </button>
                    <button
                      onClick={() => selfGrade(true)}
                      className="flex-1 h-[58px] rounded-input flex items-center justify-center text-[16px] font-bold text-correct"
                      style={{ background: "rgba(155,178,101,.12)", border: "1.5px solid rgba(155,178,101,.5)" }}
                    >
                      Gewusst
                    </button>
                  </div>
                </div>
              </>
            )}

            {/* WEITER button (feedback only) */}
            {cardPhase === "feedback" && (
              <div className="absolute left-[22px] right-[22px] bottom-9">
                <div className="text-center text-[13px] font-semibold text-faint mb-[13px]">
                  → wischen für »Weiter«
                </div>
                <button
                  onClick={nextCard}
                  className="w-full h-[60px] rounded-pill bg-accent text-on-accent flex items-center justify-center text-[18px] font-extrabold"
                >
                  Weiter
                </button>
              </div>
            )}
          </>
        )}

        {/* Exit overlay */}
        {exitOpen && (
          <ExitOverlay
            busy={ending}
            onContinue={() => setExitOpen(false)}
            onEnd={endSession}
          />
        )}
      </div>
    )
  }

  // ---- CHAT SCREEN ----
  return (
    <div className="bg-bg w-full max-w-md mx-auto flex flex-col pt-safe md:border-x md:border-border" style={{ height: "100dvh" }}>
      {/* Chat header */}
      <div className="px-4 pt-3 pb-[14px] flex items-center gap-2.5 shrink-0">
        <button
          onClick={() => setExitOpen(true)}
          className="w-[38px] h-[38px] rounded-full bg-surface border border-border flex items-center justify-center text-[20px] text-muted flex-shrink-0"
        >
          ‹
        </button>
        <div className="flex-1">
          <div className="text-[11px] font-extrabold uppercase text-muted"
            style={{ letterSpacing: "0.1em", fontFamily: "'Hanken Grotesk', sans-serif" }}>
            Neuer Stoff
          </div>
          <div className="text-[16px] font-extrabold mt-0.5">{phaseLabel || "Phase 1"}</div>
        </div>
        <button
          onClick={endSession}
          disabled={ending}
          className="text-[14px] font-extrabold text-accent-bright px-[14px] py-2 rounded-pill disabled:opacity-50"
          style={{ background: "rgba(213,123,72,.12)" }}
        >
          Fertig
        </button>
      </div>

      {/* Messages */}
      <div
        ref={scrollRef}
        className="flex-1 min-h-0 px-[18px] overflow-y-auto flex flex-col gap-[13px]"
      >
        {chat.filter((m) => !m.hidden).map((m, i) => (
          <ChatBubble key={i} role={m.role} text={m.text} />
        ))}
        {pending && <ChatBubble role="tutor" text="" isTyping />}
      </div>

      {/* Input dock */}
      <div className="px-[14px] pt-2 pb-4 bg-bg shrink-0">
        <div className="flex items-center gap-2.5">
          <input
            value={chatInput}
            onChange={(e) => setChatInput(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); sendChat() } }}
            placeholder="Auf Türkisch antworten…"
            autoComplete="off"
            autoCapitalize="off"
            spellCheck={false}
            className="flex-1 h-[52px] rounded-input bg-surface text-text px-5 text-[16px] font-medium outline-none"
            style={{ border: "1.5px solid #3f3429", fontSize: "16px" }}
          />
          <button
            onClick={sendChat}
            disabled={pending}
            className="w-[52px] h-[52px] rounded-full bg-accent text-on-accent flex items-center justify-center text-[22px] font-extrabold flex-shrink-0 disabled:opacity-50"
          >
            →
          </button>
        </div>
      </div>

      {exitOpen && (
        <ExitOverlay
          busy={ending}
          onContinue={() => setExitOpen(false)}
          onEnd={endSession}
        />
      )}
    </div>
  )
}

function ExitOverlay({ busy, onContinue, onEnd }: { busy: boolean; onContinue: () => void; onEnd: () => void }) {
  return (
    <div
      className="fixed inset-0 flex items-center justify-center px-[26px] z-50"
      style={{ background: "rgba(10,7,4,.74)" }}
    >
      <div className="w-full max-w-md bg-surface border border-border rounded-card px-[26px] py-[30px] text-center"
        style={{ boxShadow: "0 24px 50px -16px rgba(0,0,0,.7)" }}>
        <div className="text-[22px] font-extrabold">Sitzung beenden?</div>
        <div className="text-[14.5px] font-medium text-muted mt-2.5 leading-relaxed">
          Dein Fortschritt für diese Runde wird gespeichert.
        </div>
        <button
          onClick={onContinue}
          disabled={busy}
          className="w-full h-14 rounded-pill bg-accent text-on-accent flex items-center justify-center text-[17px] font-extrabold mt-6 disabled:opacity-50"
        >
          Weiter üben
        </button>
        <button
          onClick={onEnd}
          disabled={busy}
          className="w-full h-[50px] flex items-center justify-center text-[16px] font-bold text-wrong mt-1.5 disabled:opacity-50"
        >
          {busy ? "Speichern…" : "Beenden & speichern"}
        </button>
      </div>
    </div>
  )
}
